[package]
name = "cmsis_pdsc_parser"
description = "A CMSIS-Pack PDSC file parser for Rust"
keywords = ["CMSIS", "CMSIS-Pack", "PDSC", "parser"]
categories = ["api-bindings", "embedded", "parser-implementations"]
version = "0.1.0"
edition = "2024"
readme = "README.md"
repository = "https://github.com/sebasthg/cmsis-pdsc-parser"
license = "MIT"

[[test]]
name = "PIC32CM_PL"
harness = false

[dependencies]
log = "0.4.33"
roxmltree = "0.21.1"
serde = { version = "1.0.229", features = ["derive"] }
serde-roxmltree = { version = "0.11.2", features = ["raw-node"] }

[dev-dependencies]
env_logger = "0.11.11"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
doc_markdown = "allow"
nursery = { level = "deny", priority = -1 }
# DENY PANICS:
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"