//! Contains types representing debug sequences

use std::{collections::HashMap, fmt::Debug};
use serde::{Deserialize, Serialize, de::value};
use log::{debug, error, trace, warn};

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents [PDSC Package](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_package_pg.html)
/// which is the root element of the PDSC file
pub struct Package {
    pub devices: Devices
}

impl Package {
    pub fn new(pdsc_content: &str) -> Self {
        // Parse the content
        let mut pdsc: Self = serde_roxmltree::from_str(&pdsc_content).unwrap();

        // Parse the "wild" string conents into structured data
        pdsc.devices.family.debugvars.parse_debugvars();

        // Return the data
        pdsc
    }
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents [PDSC Devices](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_devices_pg.html)
pub struct Devices {
    pub family: Family
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents [PDSC Family](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html)
pub struct Family {
    #[serde(rename = "Dfamily")]
    /// The device family name
    pub device_family: String,

    #[serde(rename = "Dvendor")]
    /// The device manufacturer/vendor
    pub vendor: String, // TODO: Make enum

    /// Global debug variables
    pub debugvars: Debugvars,

    /// Debug sequences
    pub sequences: Sequences
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents the `traceSetput` attribute in [PDSC sequences](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_sequences)
enum TraceSetup {
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "legacy")]
    Legacy
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents [PDSC sequences](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_sequences)
pub struct Sequences {
    /// Trace setup configuration
    #[serde(rename = "traceSetup")]
    trace_setup: Option<TraceSetup>,

    /// Debug sequences
    #[serde(rename = "sequence")]
    pub sequences: Vec<Sequence>
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents [PDSC Debugvars](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_debugvars)
pub struct Debugvars {
    /// The relative path to the configuration file containing debugvars
    pub configfile: Option<String>,

    /// Debugvars version
    pub version: Option<String>,

    #[serde(rename = "#content")]
    /// Debugvars variable declarations
    content: String,

    /// Parsed debugvars, initially `None`, generated by [Debugvars::parse_debugvars]
    pub parsed_debugvars: Option<HashMap<String, u64>>
}

impl Debugvars {
    /// Parses a debugvar value string into u64
    fn parse_value_string(value: &str) -> Option<u64> {
            // Try to parse the value as a hex value firs
            if let Some(hex_value_str) = value.strip_prefix("0x") {
                if let Ok(k) = u64::from_str_radix(hex_value_str, 16) {
                    return Some(k);
                }
            };

            // If not hex, parse as base-10
            match value.parse() {
                Ok(k) => return Some(k),
                Err(e) => {
                    error!("Failed to parse debugvar value ({}) to u64 with error: {}", value, e);
                    return None
                }
            }
    }

    /// Parses a single variable declaration entry
    fn parse_single_debugvar(line: &str) -> Option<(String, u64)> { // TODO: Make Result
        trace!("Parsing debugvar line: {}", line);

        // Remove comments
        let declaration = if line.trim_start().starts_with("//") {
            let parts: Vec<&str> = line.split("\n").collect();
            parts[1].trim()
        } else {
            line.trim()
        };

        let stripped_declaration = match declaration.strip_prefix("__var ") {
            Some(val) => val,
            None => {
                if declaration.len() != 0 {
                    warn!("Variable in debugvars does not start with \"__var \": {:?}", declaration);
                };
                return None;
            }
        };

        let parts: Vec<&str> = stripped_declaration.split("=").collect();
        if parts.len() != 2 {
            warn!("Got something other than 2 fields when parsing debugvar: {:?}", parts);
            return None;
        }

        let name: String = parts[0].trim().to_string();
        let value_str = parts[1].trim();

        if let Some(value) = Self::parse_value_string(value_str) {
            Some((name, value))
        } else {
            None
        }
    }

    /// Parses the debugvars content and returns a hashmap with the variable name as the key and the value as the value
    pub fn parse_debugvars_content(&self) -> HashMap<String, u64> {
        // Remove any lines starting with "//"
        let content: String = self.content.split("\n").filter_map(|line| {
            if line.trim().starts_with("//") {
                trace!("Ignoring line: {}", line);
                None
            } else {
                Some(line.to_owned() + "\n") // Add back the newline
            }
        }).collect();

        // Variables are split with a ';'
        // While unlikely the spec does not forbid multiple inline assignments, e.g.:
        //    __var foo = 5; __var bar = 0x42;
        // As such we must split on ';' rather than '\n' for actual parsing.
        let variables: Vec<&str> = content.split(';').collect();

        variables.iter().filter_map(|var| {
            // Parse the variable
            Self::parse_single_debugvar(var)
        }).collect()
    }

    /// Performs the parsing and stores values in [Self::parsed_debugvars]
    pub fn parse_debugvars(&mut self) {
        let vars = self.parse_debugvars_content();

        self.parsed_debugvars = Some(vars);
    }
}


#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents [PDSC Sequence](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_sequence)
pub struct Sequence {
    /// The sequence name
    name: String,

    /// Processor name, if set only use the debug sequence for this processor
    processor_name: Option<String>,

    /// If set disable the [Predefined Debug Access Sequence](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/debug_description.html#default_sequences) of the same name
    disable: Option<bool>,

    /// Descriptive text about the sequence
    info: Option<String>,

    /// Child elements in the sequence
    #[serde(rename = "#content")]
    elements: Vec<SequenceElement>
}

//#[derive(Debug, PartialEq, Deserialize, Serialize)]
// /// Represents the valid sequence child elements as defined in the "Child Elements" section of the [PDSC sequence element](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_sequence)
/*
pub struct SequenceElements {
    #[serde(rename = "control")]
    control: Option<Vec<SequenceControl>>,
    #[serde(rename = "block")]
    block: Option<Vec<SequenceBlock>>,
    //#[serde(rename = "#missing")]
    //missing: String
}
*/

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents the valid sequence child elements as defined in the "Child Elements" section of the [PDSC sequence element](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_sequence)
pub struct SequenceElement {
    #[serde(rename = "control")]
    control: Option<SequenceControl>,
    #[serde(rename = "block")]
    block: Option<SequenceBlock>,
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents a [PDSC Control Sequence](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_seq_control)
pub struct SequenceControl {
    /// If conditional
    #[serde(rename = "if")]
    conditional_if: Option<String>,

    /// While conditional
    #[serde(rename = "while")]
    conditional_while: Option<String>,

    /// Timeout in microseconds, a value of 0 is the same as None
    timeout: Option<u64>,

    /// Child elements in the sequence
    #[serde(rename = "#content")]
    elements: Vec<SequenceElement>
}

#[derive(Debug, PartialEq, Deserialize, Serialize)]
/// Represents a [PDSC Block Sequence](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_seq_block)
pub struct SequenceBlock {
    /// If `Some(true)` the block must be executed atomically, see the description on CMSIS Pack website.
    atomic: Option<bool>,

    /// Decsriptive text, e.g. for diagnostics
    info: Option<String>,

    #[serde(rename = "#content")]
    /// Sequence block content
    content: String
}